### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'version'

### ISSUE THREAD

**Issue by mamadpierre** [AnujMahajanOxf/MAVEN#10]
I pip installed the dependencies from```requirements.txt``` of PYMARL on python3.6 and I don't think there is a problem with dependencies, but I keep receiving the following error when I run the experiment ```python src/main.py --config=noisemix_episode --env-config=sc2 with env_args.map_name=3s5z```    

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mop216/MAVEN/maven_code/src/runners/parallel_runner.py", line 311, in env_worker
    env = env_fn.x()
  File "/home/mop216/MAVEN/maven_code/src/envs/__init__.py", line 7, in env_fn
    return env(**kwargs)
  File "/home/mop216/MAVEN/maven_code/src/envs/starcraft2/starcraft2.py", line 142, in __init__
    self._launch()
  File "/home/mop216/MAVEN/maven_code/src/envs/starcraft2/starcraft2.py", line 206, in _launch
    self._sc2_proc = self._run_config.start(version=self.game_version, window_size=self.window_size)
  File "/home/mop216/MAVENN/lib64/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/mop216/MAVENN/lib64/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
TypeError: type object got multiple values for keyword argument 'version'
```
Please note that ```--config=noise_qmix_parallel --env-config=nmatrix``` configuration runs properly and uses ```nmatrix``` environment. I think there goes something wrong with the ```starcraft2.py``` which I cannot figure it out.

**Comment by Marioooooooooooooo** [comment]
I have the same problem as you, how to solve it
