### ISSUE TITLE
Error when loading environment

### ISSUE THREAD

**Issue by saizhang0218** [AnujMahajanOxf/MAVEN#2]
Hi, I saw the following error when the code runs:

"Process Process-1:
Traceback (most recent call last):
  File "/home/jovyan/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/jovyan/miniconda3/envs/pytorch/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jovyan/MAVEN/maven_code/src/runners/parallel_runner.py", line 311, in env_worker
    env = env_fn.x()
  File "/home/jovyan/MAVEN/maven_code/src/envs/__init__.py", line 7, in env_fn
    return env(**kwargs)
  File "/home/jovyan/MAVEN/maven_code/src/envs/starcraft2/starcraft2.py", line 142, in __init__
    self._launch()
  File "/home/jovyan/MAVEN/maven_code/src/envs/starcraft2/starcraft2.py", line 206, in _launch
    self._sc2_proc = self._run_config.start(version=self.game_version, window_size=self.window_size)
  File "/home/jovyan/miniconda3/envs/pytorch/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 205, in start
    want_rgb=want_rgb, extra_args=extra_args, **kwargs)
  File "/home/jovyan/miniconda3/envs/pytorch/lib/python3.6/site-packages/pysc2/run_configs/platforms.py", line 88, in start
    self, exec_path=exec_path, version=self.version, **kwargs)
TypeError: type object got multiple values for keyword argument 'version'"

Do you have any idea on this? Also can you share your "requirement.txt" so I can know which version of the tool I should use? Many thanks!

**Comment by AnujMahajanOxf** [comment]
Hi,

This seems like a version specific issue. I would recommend using docker to run the experiments. You can find the requirements in the dockerfile or the pymarl code base: https://github.com/oxwhirl/pymarl

Cheers,
Anuj
________________________________
