### ISSUE TITLE
Training 6h_vs_8z failed

### ISSUE THREAD

**Issue by GoingMyWay** [AnujMahajanOxf/MAVEN#8]
Hi, I tried to run the code on `6h_vs_8z` and failed. It shows something wrong in the `starcraft2.py`. And I also found `6h_vs_8z` is not a registered game in your code. Could you please help me to fix it?

PySC2==3.0

```
Traceback (most recent call last):
  File "/home/me/anaconda3/envs/sc_ray/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/me/anaconda3/envs/sc_ray/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/maven/maven_code/src/runners/parallel_runner.py", line 333, in env_worker
    env.reset()
  File "/home/me/maven/maven_code/src/envs/starcraft2/starcraft2.py", line 270, in reset
    return self.get_obs(), self.get_state()
  File "/home/me/maven/maven_code/src/envs/starcraft2/starcraft2.py", line 878, in get_state
    ally_state[al_id, 1] = al_unit.weapon_cooldown / max_cd # cooldown
TypeError: unsupported operand type(s) for /: 'float' and 'NoneType'
```

**Comment by GoingMyWay** [comment]
I think the easiest way to solve this issue is to use the newest SMAC without calling the env defined in this repo.
